# Generated by Django 6.0.2 on 2026-05-19 02:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsulta', '0003_especialidade_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('disponivel', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicos', models.ManyToManyField(related_name='horarios', to='teleconsulta.medico')),
            ],
            options={
                'db_table': 'horarios',
                'ordering': ['data_hora_inicio'],
            },
        ),
    ]
