# Generated by Django 6.0.2 on 2026-05-19 02:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsulta', '0004_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESERVADA', 'Reservada'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='DISPONIVEL', max_length=30)),
                ('link_video', models.URLField(blank=True, null=True)),
                ('codigo_acesso', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='teleconsulta.horario')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='teleconsulta.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='teleconsulta.paciente')),
            ],
            options={
                'db_table': 'consultas',
            },
        ),
    ]
