name: CI - Frontend

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Rodar build
        run: npm run build

      - name: Rodar app em background
        run: npm run dev &

      - name: Esperar subir servidor
        run: npx wait-on http://localhost:5173

      - name: Rodar Cypress
        run: npx cypress run